watch_stylesheet: true
watch_config: true
debug: false
komorebi:
  start_command: 'komorebic start --ahk'
  stop_command: 'komorebic stop --ahk'
  reload_command: 'komorebic stop --ahk && komorebic start --ahk'
bars:
  primary-bar:
    enabled: true
    screens: ['*']
    class_name: 'yasb-bar'
    alignment:
      position: 'top'
      center: false
    blur_effect:
      enabled: true
      acrylic: true
      dark_mode: true
      round_corners: true
      border_color: None
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: '100%'
      height: 32
    padding:
      top: 5
      left: 5
      bottom: 5
      right: 5
    widgets:
      left:
        [
          'home',
          'komorebi_active_layout',
          'notifications',
          'komorebi_workspaces',
          'active_window',
        ]
      center: [
          'clock',
          #        "taskbar"
        ]
      right: [
          #        "systray",
          'memory',
          'disk',
          'weather',
          'wifi',
          'volume',
          'battery',
          'power_menu',
        ]
widgets:
  systray:
    type: 'yasb.systray.SystrayWidget'
    options:
      class_name: 'systray'
      label_collapsed: '▼'
      label_expanded: '▶'
      label_position: 'left' # Can be "left" or "right"
      icon_size: 16 # Can be any integer between 8 and 64
      pin_click_modifier: 'alt' # Can be "ctrl", "alt" or "shift"
      show_unpinned: true
      show_unpinned_button: true
      show_battery: false
      show_volume: false
      show_network: false
      #      container_padding:
      #        left: 0
      #        top: 0
      #        right: 0
      #        bottom: 0
      btn_shadow:
        enabled: true
        color: 'black'
        radius: 3
        offset: [1, 1]
  home:
    type: 'yasb.home.HomeWidget'
    options:
      label: '<span>\udb80\udf5c</span>'
      menu_list:
        - { title: 'Home', path: '~' }
        - { title: 'Downloads', path: "~\\Downloads" }
        - { title: 'Documents', path: "~\\Documents" }
        - { title: 'Pictures', path: "~\\Pictures" }
        - { title: 'Videos', path: "~\\Videos" }
      system_menu: true
      power_menu: false
      blur: true
      round_corners: true
      round_corners_type: 'small'
      border_color: '#7aa2f7'
      alignment: 'left'
      offset_left: 4
      offset_top: 0
  komorebi_active_layout:
    type: 'komorebi.active_layout.ActiveLayoutWidget'
    options:
      hide_if_offline: true
      label: '{icon} {layout_name}'
      layouts:
        [
          'bsp',
          'columns',
          'rows',
          'grid',
          'vertical_stack',
          'horizontal_stack',
          'ultrawide_vertical_stack',
          'right_main_vertical_stack',
        ]
      layout_icons:
        bsp: '\uebeb'
        columns: '\uebf7'
        rows: '\uec01'
        grid: '\udb81\udf58'
        vertical_stack: '\uebee'
        horizontal_stack: '\uebf0'
        ultrawide_vertical_stack: '\uebee'
        right_main_vertical_stack: '\uebf1'
        monocle: '\uf06f'
        maximised: '\uf06f'
        floating: '\uf2d2'
        paused: '\udb83\udf89'
      #        tiling: "\udb81\ude40"
      callbacks:
        #        on_left: 'toggle_layout_menu'
        on_middle: 'next_layout'
        on_right: 'prev_layout'
      #      layout_menu:
      #        blur: true
      #        round_corners: true
      #        round_corners_type: "normal"
      #        border_color: "System"
      #        alignment: "left"
      #        direction: "down"
      #        offset_top: 6
      #        offset_left: 0
      #        show_layout_icons: true
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 8
      label_shadow:
        enabled: true
        color: 'black'
        radius: 3
        offset: [1, 1]
  notifications:
    type: 'yasb.notifications.NotificationsWidget'
    options:
      label: '<span>\uf476</span> {count}'
      label_alt: '{count} notifications'
      hide_empty: true
      tooltip: false
      callbacks:
        on_left: 'toggle_notification'
        on_right: 'do_nothing'
        on_middle: 'toggle_label'
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 8
      label_shadow:
        enabled: true
        color: 'black'
        radius: 3
        offset: [1, 1]
  komorebi_workspaces:
    type: 'komorebi.workspaces.WorkspaceWidget'
    options:
      label_offline: 'Komorebi Offline'
      label_workspace_btn: '\udb81\udc3d'
      label_workspace_active_btn: '\udb81\udc3e'
      label_workspace_populated_btn: '\udb81\udc3e'
      label_default_name: ''
      label_zero_index: false
      hide_empty_workspaces: false
      hide_if_offline: true
      animation: true
      toggle_workspace_layer:
        enabled: false
        tiling_label: 'Tiling'
        floating_label: 'Floating'
      #      app_icons:
      #        enabled_populated: false
      #        enabled_active: false
      #        size: 12
      #        max_icons: 0
      #        hide_label: false
      #        hide_duplicates: false
      #        hide_floating: false
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 8
      btn_shadow:
        enabled: true
        color: 'black'
        radius: 3
        offset: [1, 1]
  taskbar:
    type: 'yasb.taskbar.TaskbarWidget'
    options:
      icon_size: 16
      animation:
        enabled: true
        duration: 200
        type: 'fadeInOut'
      title_label:
        enabled: false
        show: 'focused'
        min_length: 10
        max_length: 30
      ignore_apps:
        processes: []
        titles: []
        classes: []
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 8
  memory:
    type: 'yasb.memory.MemoryWidget'
    options:
      label: '<span>\uf4bc</span> {virtual_mem_outof}'
      label_alt: '<span>\uf4bc</span> {virtual_mem_outof}'
      update_interval: 10000
      callbacks:
        on_right: 'exec cmd /c Taskmgr'
  disk:
    type: 'yasb.disk.DiskWidget'
    options:
      label: '<span>\uf473</span> disks'
      label_alt: '<span>\uf473</span>'
      group_label:
        volume_labels:
          [
            'C',
            'D',
            'E',
            'F',
            'G',
            'H',
            'I',
            'J',
            'K',
            'L',
            'M',
            'N',
            'O',
            'P',
            'Q',
            'R',
            'S',
            'T',
            'U',
            'V',
            'W',
            'X',
            'Y',
            'Z',
          ]
        show_label_name: false
        blur: true
        round_corners: true
        round_corners_type: 'small'
        border_color: '#7aa2f7'
        alignment: 'center'
        offset_top: 0
      callbacks:
        on_left: 'toggle_group'
  active_window:
    type: 'yasb.active_window.ActiveWindowWidget'
    options:
      label: '{win[title]}'
      label_alt: "[class_name='{win[class_name]}' exe='{win[process][name]}' hwnd={win[hwnd]}]"
      label_no_window: ''
      label_icon: true
      label_icon_size: 14
      max_length: 50
      max_length_ellipsis: '...'
      monitor_exclusive: true
  clock:
    type: 'yasb.clock.ClockWidget'
    options:
      label: '<span>\uf017</span>{%H:%M}'
      label_alt: '<span>\uf017</span>{%A, %B %d. %Y %H:%M}'
      locale: 'hu_HU'
      timezones: []
      calendar:
        round_corners: true
        round_corners_type: 'small'
        border_color: '#7aa2f7'
        alignment: 'center'
        offset_top: 0
  weather:
    type: 'yasb.weather.WeatherWidget'
    options:
      label: '<span>{icon}</span> {temp}'
      label_alt: '{location}: {conditions}, Min {min_temp}, Max {max_temp}, Humidity {humidity}'
      api_key: '24b6c2cda6d84066b0304531241908' # gitleaks:allow
      update_interval: 600
      hide_decimal: true
      location: 'Hungary, Eger'
      units: 'metric'
      callbacks:
        on_left: 'toggle_card'
      icons:
        sunnyDay: '\udb81\udd99'
        clearNight: '\ue3c2'
        cloudyDay: '\ue21d'
        cloudyNight: '\ue226'
        rainyDay: '\ue371'
        rainyNight: '\ue371'
        snowyIcyDay: '\udb81\udf17'
        snowyIcyNight: '\udb81\udf17'
        blizzard: '\udb81\udd99'
        default: '\udb81\udd99'
      weather_card:
        blur: true
        round_corners: true
        round_corners_type: 'small'
        border_color: '#7aa2f7'
        alignment: 'center'
        direction: 'down'
        offset_top: 0
        icon_size: 48
  wifi:
    type: 'yasb.wifi.WifiWidget'
    options:
      label: '<span>{wifi_icon}</span> {wifi_strength}%'
      label_alt: '<span>{wifi_icon}</span> {wifi_name} {wifi_strength}%'
      ethernet_label: '<span>{wifi_icon}</span>'
      ethernet_label_alt: '<span>{wifi_icon}</span> {wifi_name}'
      ethernet_icon: '\uf108'
      update_interval: 5000
      callbacks:
        on_left: 'exec quick_settings'
        on_middle: 'do_nothing'
        on_right: 'toggle_label'
      wifi_icons: [
          '\udb82\udd2e', # Icon for 0% strength
          '\udb82\udd1f', # Icon for 1-20% strength
          '\udb82\udd22', # Icon for 21-40% strength
          '\udb82\udd25', # Icon for 41-80% strength
          '\udb82\udd28', # Icon for 81-100% strength
        ]
  volume:
    type: 'yasb.volume.VolumeWidget'
    options:
      label: '<span>{icon}</span> {level}'
      label_alt: '{volume}'
      volume_icons:
        - '\ueee8' # Icon for muted
        - '\uf026' # Icon for 0-10% volume
        - '\uf027' # Icon for 11-30% volume
        - '\uf027' # Icon for 31-60% volume
        - '\uf028' # Icon for 61-100% volume
      audio_menu:
        blur: true
        round_corners: true
        round_corners_type: 'small'
        border_color: '#7aa2f7'
        alignment: 'center'
        direction: 'down'
        offset_top: 0
      callbacks:
        on_right: 'toggle_mute'
  battery:
    type: 'yasb.battery.BatteryWidget'
    options:
      label: '<span>{icon}</span>{percent}%'
      label_alt: '<span>{icon}</span> {percent}% | time: {time_remaining}'
      #hide_unsupported: true
      charging_options:
        icon_format: '{charging_icon}'
  power_menu:
    type: 'yasb.power_menu.PowerMenuWidget'
    options:
      label: '\uf011'
      uptime: True
      blur: False
      blur_background: True
      animation_duration: 200
      button_row: 5
      buttons:
        shutdown: ['\uf011', 'Shut Down']
        restart: ['\uead2', 'Restart']
        signout: ['\udb80\udf43', 'Sign out']
        hibernate: ['\uf28e', 'Hibernate']
        sleep: ['\u23fe', 'Sleep']
        cancel: ['', 'Cancel']
