# Gitleaks configuration file
# This file configures gitleaks to detect secrets in your repository

# Customize this configuration to fit your project's needs
# For more information, see: https://github.com/zricethezav/gitleaks/blob/master/config/gitleaks.toml

title = "Gitleaks Config"

# Extend the base config from the gitleaks default
[extend]
useDefault = true

# Additional or custom rules can be added here
[[rules]]
id = "bitwarden-access-token"
description = "Bitwarden BWS Access Token"
regex = '''(?i)bws_[a-z0-9]{32}'''
keywords = ["bws_"]

[[rules]]
id = "kubernetes-config"
description = "Kubernetes config secret"
regex = '''(?i)(certificate-authority-data|client-certificate-data|client-key-data)\s*:\s*[A-Za-z0-9+/]{100,}={0,2}'''
keywords = ["certificate-authority-data", "client-certificate-data", "client-key-data"]

# File types to allow (whitelist)
[allowlist]
description = "Allow certain file types"
files = [
    '''(?i)\.md$''',           # Markdown files
    '''(?i)\.txt$''',          # Text files
    '''(?i)\.yaml$''',         # YAML files (be careful with this)
    '''(?i)\.yml$''',          # YAML files (be careful with this)
    '''(?i)\.json$''',         # JSON files (be careful with this)
]

# Paths to ignore
paths = [
    '''(?i)\.git/''',          # Git directory
    '''(?i)node_modules/''',   # Node modules
    '''(?i)vendor/''',         # Vendor directory
    '''(?i)\.vscode/''',       # VS Code settings
    '''(?i)\.idea/''',         # IntelliJ IDEA settings
]

# Regexes to allow (whitelist)
regexes = [
    '''(?i)example\.com''',    # Example domains
    '''(?i)localhost''',       # Localhost
    '''(?i)127\.0\.0\.1''',    # Local IP
    '''(?i)0\.0\.0\.0''',      # Bind all interfaces
    '''(?i)::1''',             # IPv6 localhost
]

# Keywords to allow in certain contexts
keywords = [
    "password",
    "secret",
    "token",
    "key",
    "api",
    "auth",
]
