# Prettier configuration for consistent code formatting
# See https://prettier.io/docs/en/configuration.html

# Basic formatting rules
tabWidth: 2
useTabs: false
semi: true
singleQuote: true
quoteProps: "as-needed"
trailingComma: "es5"
bracketSpacing: true
bracketSameLine: false
arrowParens: "avoid"

# Line wrapping
printWidth: 88
proseWrap: "preserve"

# Language-specific overrides
overrides:
  - files: "*.md"
    options:
      tabWidth: 2
      printWidth: 88
      proseWrap: "always"

  - files: "*.yml"
    options:
      tabWidth: 2
      singleQuote: false

  - files: "*.yaml"
    options:
      tabWidth: 2
      singleQuote: false

  - files: "*.json"
    options:
      tabWidth: 2
      trailingComma: "none"
