# This script ensures the BWS_ACCESS_TOKEN environment variable is set
# It runs before other scripts that may need to access Bitwarden

# Check if BWS_ACCESS_TOKEN is already set
if (-not [Environment]::GetEnvironmentVariable('BWS_ACCESS_TOKEN', 'Process')) {
    Write-Host "Setting up Bitwarden access token..."

    # Option 2: Ask for it interactively
        Write-Host "Bitwarden access token not found."
        $token = Read-Host "Enter your Bitwarden access token"
        [Environment]::SetEnvironmentVariable('BWS_ACCESS_TOKEN', $token, 'Process')
}

# Verify we have a token
if ([Environment]::GetEnvironmentVariable('BWS_ACCESS_TOKEN', 'Process')) {
    Write-Host "BWS_ACCESS_TOKEN is set and ready to use."

    # Export to a temporary file that other scripts can source
    # This is useful for scripts that run in separate PowerShell instances
    $content = "# Auto-generated by chezmoi`r`n`$env:BWS_ACCESS_TOKEN = '$([Environment]::GetEnvironmentVariable('BWS_ACCESS_TOKEN', 'Process'))'"
    $content | Out-File -FilePath "$env:USERPROFILE\.chezmoi_bw_token.ps1" -Force
}
else {
    Write-Error "ERROR: BWS_ACCESS_TOKEN is not set and could not be retrieved automatically."
    Write-Host "Please set BWS_ACCESS_TOKEN manually before running chezmoi."
    exit 1
}
